# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{- $this := dict "gp" .Values "comp" .Values.components.db -}}
{{- if not $this.comp.gcloudSqlProxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: db-password
  labels:
    app: {{ template "gitpod.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mysql-root-password: {{ include "gitpod.secret-db-password" $this.gp | b64enc | quote }}
{{- end }}
