# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{- define "gitpod.messageBus.auth" -}}
{{- with .Values.rabbitmq.auth }}
{{- if (and .username .password) }}
  username: .username
  password: .password
{{- else if .existingAuthSecret }}
{{- $gitpod.rabbitmq.auth.secret := lookup "v1" "Secret" .existingAuthSecret }}
  username: index ($gitpod.rabbitmq.auth.secret).data "username"
  password: index ($gitpod.rabbitmq.auth.secret).data "password"
{{- else }}
  username: ""
  password: ""
{{- end }}
{{- end }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: messagebus-certificates-secret-core
  labels:
    app: {{ template "gitpod.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ca.crt:  {{ .Files.Get "secrets/messagebus/msgbus-ca.pem" | b64enc | quote }}
  tls.crt: {{ .Files.Get "secrets/messagebus/msgbus-client.crt" | b64enc | quote }}
  tls.key:  {{ .Files.Get "secrets/messagebus/msgbus-client.pem"| b64enc | quote }}
  username: {{ (include "gitpod.messageBus.auth").username | b64enc | quote }}                      
  password: {{ (include "gitpod.messageBus.auth").password | b64enc | quote }}                      

